services:
  base:
    image: lucidjs
    build:
      context: .
      target: development

  web:
    image: lucidjs
    command: npm run dev --workspace=packages/web -- --host 0.0.0.0
    volumes:
      - .:/app
      - web_root_modules:/app/node_modules/
      - web_workspace_modules:/app/packages/web/node_modules/
    ports:
      - "3001:3001"

  native:
    image: lucidjs
    volumes:
      - .:/app
      - native_root_modules:/app/node_modules/
      - native_workspace_modules:/app/packages/native/node_modules/
    ports:
      - "4001:4001"

  desktop:
    image: lucidjs
    command: npm run tauri dev --workspaces/desktop
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/app
      - desktop_root_modules:/app/node_modules/
      - desktop_workspace_modules:/app/packages/desktop/node_modules/
      - desktop_target:/app/packages/desktop/src-tauri/target
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "2001:2001"

  server-template:
    image: lucidjs
    command: npm run dev --workspace=templates/server
    volumes:
      - .:/app
      - server-template_root_modules:/app/node_modules
      - server-template_workspace_modules:/app/templates/server/node_modules
    ports:
      - "5001:5001"

volumes:
  web_root_modules:
  web_workspace_modules:
  native_root_modules:
  native_workspace_modules:
  desktop_root_modules:
  desktop_workspace_modules:
  desktop_target:
  server-template_root_modules:
  server-template_workspace_modules:
